[package]
name = "ship_shell"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
nix = "0.30.1"
pyo3 = { version = "0.27.1", features = ["anyhow", "auto-initialize"] }
rustyline = "17.0.2"
signal-hook = "0.3.18"
which = "8.0"
